### ISSUE TITLE
How to RUN

### ISSUE THREAD

**Issue by ShahariarRabby** [kaftanski/fissure-segmentation#1]
Thank you for the project. 

Can you add a readme about how to run the project? Also, is there a way where I can read your thesis paper?

**Comment by kaftanski** [comment]
Hi thank you for your interest in the project!
We have just published a cleaned up version of this repository at https://github.com/kaftanski/fissure-segmentation-IJCARS (including instructions for running). If you need assistance on running that code feel free to open an issue there
